version: '3.4'

services:
  dtale_2_7:
    image: dtale_2_7:latest
    environment:
      - TZ=America/New_York
    build:
      context: .
      dockerfile: docker/2_7/Dockerfile
    ports:
      - "8080:3000"
  dtale_3_6:
    image: dtale_3_6:latest
    environment:
      - TZ=America/New_York
    build:
      context: .
      dockerfile: docker/3_6/Dockerfile
    ports:
      - "80:3000"
